 'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {paymentLabel} from '@/lib/model';
import {money,amountText,parseAmount,type Currency,currencyInfo} from '@/lib/currency';
import {sendJSON} from '@/lib/offline';
import CurrencyChoice from './currency-choice';
import {useI18n} from './i18n-provider';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
type Row={method:string;sales:number;refunds:number;expected:number;actual?:number;difference?:number};
type Ledger={date:string;currency:Currency;revision:number;expected:Row[];history:{id:string;createdAt:string;counts:Row[];note:string}[]};
export default function Payments({currency:initial,online,onSaved}:{currency:Currency;online:boolean;onSaved:()=>Promise<unknown>}){
 const {t,locale}=useI18n(),[currency,setCurrency]=useState(initial),[date,setDate]=useState(()=>new Date().toISOString().slice(0,10)),[data,setData]=useState<Ledger|null>(null),[actual,setActual]=useState<Record<string,string>>({}),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{const abort=new AbortController();setData(null);setActual({});setError('');sendJSON<Ledger>('/api/payments?'+new URLSearchParams({date,currency}),{signal:abort.signal}).then(setData).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[date,currency,reload]);
 async function submit(e:FormEvent){e.preventDefault();if(!data||busy)return;setBusy(true);setError('');try{const counts=Object.fromEntries(data.expected.map(r=>{const v=actual[r.method]??'',negative=v.startsWith('-'),value=parseAmount(negative?v.slice(1):v,currency);return [r.method,negative?-value:value];}));await sendJSON('/api/payments',{method:'POST',body:JSON.stringify({id:crypto.randomUUID(),date,currency,revision:data.revision,actual:counts,note})});setNote('');setReload(n=>n+1);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel recovery-panel"><h2>{t('Daily payment check')}</h2><p>{t('Compare net payments with cash counted and mobile money or card statements. Exclude opening float and unrelated deposits or expenses.')}</p><div className="form-grid"><label>{t('Date')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{t('Currency')}<CurrencyChoice value={currency} onChange={setCurrency}/></label></div><button className="secondary" disabled={busy||!online} onClick={()=>setReload(n=>n+1)}>{t('Refresh totals')}</button>{error&&<p role="alert" className="notice warning">{t(error)}</p>}{data&&<form onSubmit={submit}><Table><TableHeader><TableRow>{['Payment method','Collected','Refunded','Expected net','Actual net','Difference'].map(x=><TableHead key={x}>{t(x)}</TableHead>)}</TableRow></TableHeader><TableBody>{data.expected.map(row=>{const raw=actual[row.method]??'',n=parseAmount(raw.startsWith('-')?raw.slice(1):raw,currency)*(raw.startsWith('-')?-1:1);return <TableRow key={row.method}><TableCell>{t(paymentLabel(row.method))}</TableCell><TableCell>{money(row.sales,currency,locale)}</TableCell><TableCell>{money(row.refunds,currency,locale)}</TableCell><TableCell>{money(row.expected,currency,locale)}</TableCell><TableCell><input aria-label={t('Actual net')+' '+t(paymentLabel(row.method))} required type="number" step={currencyInfo[currency].step} value={raw} onChange={e=>setActual(v=>({...v,[row.method]:e.target.value}))}/></TableCell><TableCell>{raw&&Number.isFinite(n)?money(n-row.expected,currency,locale):'—'}</TableCell></TableRow>;})}</TableBody></Table><label>{t('Notes')}<textarea maxLength={300} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={busy||!online}>{t('Save reconciliation')}</button><p className="form-note">{t('Unsynced sales are excluded. Sync every device before closing the day. Later sales or refunds may require another reconciliation.')}</p><h3>{t('Saved reconciliations')}</h3>{data.history.map(record=><div className="history-entry" key={record.id}><b>{new Date(record.createdAt).toLocaleString(locale)}</b><span>{t('Difference')}: {money(record.counts.reduce((n,r)=>n+(r.difference??0),0),currency,locale)}</span><p>{record.note}</p>{record.counts.map(r=><small key={r.method}>{t(paymentLabel(r.method))}: {money(r.actual??0,currency,locale)} · {t('Difference')} {money(r.difference??0,currency,locale)}<br/></small>)}</div>)}</form>}</section>;
}
