 'use client';
import {useState,useRef,useEffect,type FormEvent} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {paymentLabel,saleCurrency,type Sale,type PaymentMethod} from '@/lib/model';
import {money,parseAmount,amountText,currencyInfo} from '@/lib/currency';
import {sendJSON,pendingOperation,keepOperation,finishOperation} from '@/lib/offline';
import PaymentChoice from './payment-choice';
import {useI18n} from './i18n-provider';
export default function RefundForm({sale,ownerId,onClose,onSaved}:{ownerId:string;sale:Sale;onClose:()=>void;onSaved:()=>Promise<void>}){
 const {t,locale}=useI18n(),currency=saleCurrency(sale),remaining=sale.total-(sale.adjustments??[]).reduce((n,a)=>n+a.amount,0);
 const [kind,setKind]=useState<'refund'|'cancel'>('refund'),[amount,setAmount]=useState(amountText(remaining,currency)),[reason,setReason]=useState(''),[method,setMethod]=useState<PaymentMethod>(sale.paymentMethod==='unspecified'||!sale.paymentMethod?'cash':sale.paymentMethod),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[locked,setLocked]=useState(false),[recovered,setRecovered]=useState(false);
 const [quantities,setQuantities]=useState<Record<string,number>>({}),[restock,setRestock]=useState<Record<string,boolean>>({}),pending=useRef<Record<string,unknown>|null>(null);
 useEffect(()=>{void pendingOperation(ownerId,'refund:'+sale.id).then(value=>{if(value){pending.current=value;setLocked(true);setAmount(amountText(value.amount,currency));setReason(value.reason);setMethod(value.paymentMethod);setKind(value.kind);setConfirmed(true);setQuantities(Object.fromEntries(value.lines.map((l:any)=>[l.productId,l.quantity])));setRestock(Object.fromEntries(value.lines.map((l:any)=>[l.productId,l.restock])));}setRecovered(true);}).catch(e=>setError(e.message));},[]);
 const available=(id:string,n:number)=>n-(sale.adjustments??[]).reduce((total,a)=>total+a.lines.filter(l=>l.productId===id).reduce((sum,l)=>sum+l.quantity,0),0);
 async function submit(e:FormEvent){e.preventDefault();if(busy||!recovered)return;setBusy(true);setError('');try{if(!pending.current)pending.current={id:crypto.randomUUID(),saleId:sale.id,kind,amount:parseAmount(amount,currency),reason,paymentMethod:method,confirmed,lines:sale.lines.filter(l=>(quantities[l.productId]??0)>0).map(l=>({productId:l.productId,quantity:quantities[l.productId],restock:restock[l.productId]===true}))};await keepOperation(ownerId,'refund:'+sale.id,pending.current);await sendJSON('/api/adjustments',{method:'POST',body:JSON.stringify(pending.current)});await finishOperation(ownerId,'refund:'+sale.id);await onSaved();onClose();}catch(e){const err=e as Error&{status?:number};setError(err.message);if(err.status&&err.status<500){await finishOperation(ownerId,'refund:'+sale.id);pending.current=null;setLocked(false);}else setLocked(true);}finally{setBusy(false);}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="app-dialog"><DialogTitle>{t('Return or refund')} · {sale.invoice}</DialogTitle><DialogDescription>{t('Keep the original invoice and add a dated adjustment. Money must be refunded outside the app.')}</DialogDescription><form onSubmit={submit} className="product-form"><fieldset disabled={busy||locked||!recovered} className="recovery-fields"><label>{t('Action')}<select value={kind} onChange={e=>{const k=e.target.value as 'refund'|'cancel';setKind(k);if(k==='cancel')setAmount(amountText(remaining,currency));}}><option value="refund">{t('Return or refund')}</option><option value="cancel">{t('Cancel invoice')}</option></select></label><label>{t('Refund amount')} ({currency})<input required type="number" min="0" max={remaining/currencyInfo[currency].factor} step={currencyInfo[currency].step} value={amount} disabled={kind==='cancel'} onChange={e=>setAmount(e.target.value)}/></label><p className="form-note">{t('Remaining refundable amount')}: {money(remaining,currency,locale)}</p><label>{t('Payment method')}<PaymentChoice value={method} onChange={setMethod}/></label><label>{t('Reason')}<textarea required maxLength={300} value={reason} onChange={e=>setReason(e.target.value)}/></label><h3>{t('Returned items')}</h3><p className="form-note">{t('Enter only goods physically returned. Select restock only for goods you can sell again.')}</p>{sale.lines.map(l=>{const max=available(l.productId,l.quantity);return <div key={l.productId} className="return-line"><label>{l.name}<input type="number" min="0" max={max} step="1" value={quantities[l.productId]??0} onChange={e=>setQuantities(q=>({...q,[l.productId]:Number(e.target.value)}))}/><small>{max} {t('available to return')}</small></label><label className="check-label"><input type="checkbox" disabled={!sale.stockDeducted} checked={restock[l.productId]??false} onChange={e=>setRestock(r=>({...r,[l.productId]:e.target.checked}))}/>{t('Restock')}</label></div>;})}<label className="check-label"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t('I have refunded this amount and checked the returned goods.')}</label></fieldset>{error&&<p role="alert" className="notice warning">{t(error)}</p>}{locked&&<p className="form-note">{t('Retry this same adjustment to confirm whether it was saved.')}</p>}<button className="primary" disabled={busy||!recovered}>{t(locked?'Retry':'Save adjustment')}</button></form></DialogContent></Dialog>;
}
