import type {Business,Product,Purchase,Sale} from './model';
export type StoreSnapshot={ownerId:string;businessId?:string;isOwner?:boolean;permissions?:('sell'|'products'|'purchase'|'refund'|'reports'|'payments'|'settings'|'recovery'|'members')[];revision:number;products:Product[];sales:Sale[];purchases:Purchase[];business:Business;backup:{created_at:string;revision:number}|null};
export type QueuedSale={key:string;ownerId:string;payload:Record<string,unknown>;sale:Sale;error?:string;review?:boolean;syncRevision?:number};
const databaseName='marketdesk-offline-v1';
let connection:Promise<IDBDatabase>|undefined;
function open(){if(!connection)connection=new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(databaseName,1);req.onupgradeneeded=()=>req.result.createObjectStore('records',{keyPath:'key'});req.onerror=()=>reject(req.error);req.onsuccess=()=>resolve(req.result);}).catch(e=>{connection=undefined;throw e;});return connection;}
async function transaction<T>(mode:IDBTransactionMode,run:(store:IDBObjectStore,set:(v:T)=>void)=>void){const db=await open();return new Promise<T>((resolve,reject)=>{const tx=db.transaction('records',mode),store=tx.objectStore('records');let value:T;tx.oncomplete=()=>resolve(value);tx.onabort=()=>reject(tx.error??new Error('Local storage unavailable.'));tx.onerror=()=>reject(tx.error);run(store,v=>{value=v;});});}
export async function readLocal(ownerId:string){return transaction<{snapshot?:StoreSnapshot;queue:QueuedSale[];operations:string[]}>('readonly',(store,set)=>{const req=store.getAll();req.onsuccess=()=>set({snapshot:req.result.find(r=>r.key===ownerId+':cache')?.value,operations:req.result.filter(r=>r.ownerId===ownerId&&r.key.startsWith(ownerId+':operation:')).map(r=>r.key),queue:req.result.filter(r=>r.ownerId===ownerId&&r.sale).sort((a,b)=>a.sale.createdAt.localeCompare(b.sale.createdAt))});});}
export async function saveSnapshot(snapshot:StoreSnapshot){return transaction<void>('readwrite',(store)=>{const cached=store.get(snapshot.ownerId+':cache');cached.onsuccess=()=>{if(!cached.result||cached.result.value.revision<=snapshot.revision)store.put({key:snapshot.ownerId+':cache',value:snapshot});};const req=store.getAll();req.onsuccess=()=>{for(const row of req.result){if(row.ownerId===snapshot.ownerId&&row.syncRevision!==undefined&&row.syncRevision<=snapshot.revision)store.delete(row.key);}};});}
export async function saveQueued(row:QueuedSale,create=false){return transaction<void>('readwrite',store=>{if(create)store.add(row);else store.put(row);});}
export async function clearLocal(ownerId:string){return transaction<void>('readwrite',store=>{const req=store.getAll();req.onsuccess=()=>{for(const row of req.result)if(row.ownerId===ownerId||row.key===ownerId+':cache')store.delete(row.key);};});}
export function availableProducts(snapshot:StoreSnapshot,queue:QueuedSale[]){return snapshot.products.map(p=>({...p,quantity:Math.max(0,p.quantity-queue.filter(q=>!(q.syncRevision!==undefined&&q.syncRevision<=snapshot.revision)&&!snapshot.sales.some(s=>s.id===q.sale.id)).reduce((n,q)=>n+(q.sale.lines.find(l=>l.productId===p.id)?.quantity??0),0))}));}
export async function sendJSON<T=any>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(path,{...options,signal:options?.signal??AbortSignal.timeout(20000),headers:{'Content-Type':'application/json',...options?.headers}});if(!response.headers.get('content-type')?.includes('application/json'))throw Object.assign(new Error('Please reconnect and sign in to sync your sales.'),{status:response.status>=500?response.status:401});const data=await response.json() as any;if(!response.ok)throw Object.assign(new Error(data.error||'Please try again.'),{status:response.status});return data;}
export async function syncSales(ownerId:string,onSaved:(sale:Sale)=>void=()=>{}){
 const work=async()=>{const current=await sendJSON<{ownerId:string}>('/api/sync');if(current.ownerId!==ownerId)throw new Error('This device is signed in to a different account. Sign in to the original account to sync.');const {queue}=await readLocal(ownerId);
 for(const row of queue){if(row.review||row.syncRevision!==undefined)continue;
  try{const sale=await sendJSON<Sale&{syncRevision:number}>('/api/sales',{method:'POST',body:JSON.stringify(row.payload)});await saveQueued({...row,sale:{...sale,pending:false},syncRevision:sale.syncRevision,error:undefined});onSaved(sale);}
  catch(e){const error=e as Error&{status?:number};if(error.status===401||error.status===403)throw error;await saveQueued({...row,error:error.message,review:!!error.status&&error.status<500});if(!error.status||error.status>=500)break;}
 }
 const snapshot=await sendJSON<StoreSnapshot>('/api/store');if(snapshot.ownerId!==ownerId)throw new Error('Account changed. Reopen your shop.');await saveSnapshot(snapshot);return readLocal(ownerId);
 };
 return navigator.locks?navigator.locks.request('marketdesk-sync-'+ownerId,work):work();
}
export function downloadJSON(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
async function workerMessage(message:unknown){return new Promise<any>((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(new Error('Offline setup timed out.')),20000);channel.port1.onmessage=e=>{clearTimeout(timer);e.data?.error?reject(new Error(e.data.error)):resolve(e.data);};void navigator.serviceWorker.ready.then(registration=>registration.active?.postMessage(message,[channel.port2])).catch(error=>{clearTimeout(timer);reject(error);});});}
export async function prepareOffline(ownerId:string){if(!('serviceWorker' in navigator))throw new Error('This browser cannot reopen the app offline.');const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/',updateViaCache:'none'});await registration.update().catch(()=>undefined);await navigator.serviceWorker.ready;await workerMessage({type:'PREPARE',ownerId,assets:performance.getEntriesByType('resource').map(r=>r.name)});void navigator.storage?.persist?.().catch(()=>false);}
export async function forgetOffline(ownerId:string){await clearLocal(ownerId);if('serviceWorker' in navigator&&(await navigator.serviceWorker.getRegistration('/'))?.active)await workerMessage({type:'CLEAR'});if('caches' in window)for(const key of await caches.keys())if(key.startsWith('marketdesk-shell-'))await caches.delete(key);}

export async function pendingOperation(ownerId:string,name:string){return transaction<any>('readonly',(store,set)=>{const req=store.get(ownerId+':operation:'+name);req.onsuccess=()=>set(req.result?.value??null);});}
export async function keepOperation(ownerId:string,name:string,value:unknown){return transaction<void>('readwrite',store=>{store.put({key:ownerId+':operation:'+name,ownerId,value});});}
export async function finishOperation(ownerId:string,name:string){return transaction<void>('readwrite',store=>{store.delete(ownerId+':operation:'+name);});}
